### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by malept** [MarshallOfSound/pruner#2]
Testcases from Forge and elsewhere:

* scoped packages
* symlinked packages (e.g., how `cnpm` works)
* packages which are both in `dependencies` and `devDependencies`
  * both direct and indirect
* `optionalDependencies`

**Comment by MarshallOfSound** [comment]
Module is deprecated in favor of [`galactus`](https://github.com/MarshallOfSound/galactus) and this is fixed over there
